root = "."
testdata_dir = "testing"
tmp_dir = "tmp"

[build]
  args_bin = []
  bin = ""
  cmd = "go build -o ./tmp/main ./cmd/app/main.go"
  delay = 100
  exclude_dir = ["assets", "tmp", "vendor", "testing", "swagger"]
  exclude_file = []
  exclude_regex = ["_test.go", ".md"]
  exclude_unchanged = false
  follow_symlink = false
  full_bin = "swag fmt && swag init -g ./cmd/app/main.go --output swagger --quiet && ./tmp/main server --env-path=.env --mode=DEVELOPMENT"
  include_dir = []
  include_ext = ["go", "tpl", "tmpl", "html"]
  include_file = []
  kill_delay = "0s"
  log = "build-errors.log"
  poll = false
  poll_interval = 0
  rerun = false
  rerun_delay = 500
  send_interrupt = false
  stop_on_error = false

[color]
  app = ""
  build = "yellow"
  main = "magenta"
  runner = "green"
  watcher = "cyan"

[log]
  main_only = false
  time = false

[misc]
  clean_on_exit = false

[screen]
  clear_on_rebuild = false
  keep_scroll = true
