# (mandatory) 
# Path to coverprofile file (output of `go test -coverprofile` command)
profile: cover.out

# (optional) 
# When specified reported file paths will not contain local prefix in the output
local-prefix: "github.com/rmscoal/moilerplate"

# Holds coverage thresholds percentages, values should be in range [0-100]
threshold:
  # (optional; default 0) 
  # The minimum coverage that each file should have
  file: 70

  # (optional; default 0) 
  # The minimum coverage that each package should have
  package: 70

  # (optional; default 0) 
  # The minimum total coverage project should have
  total: 80

# Holds regexp rules which will override thresholds for matched files or packages using their paths.
#
# First rule from this list that matches file or package is going to apply new threshold to it. 
# If project has multiple rules that match same path, override rules should be listed in order from 
# specific to more general rules.
override:
  # Increase coverage threshold to 100% for `utils` package
  - threshold: 100
    path: ^internal/utils$

  # Increase coverage threshold to 95% for `repo` package
  - threshold: 90
    path: ^internal/adapter/repo$

  # Increase coverage threshold to 95% for `usecase` package
  - threshold: 90
    path: ^internal/app/usecase$

# Holds regexp rules which will exclude matched files or packages from coverage statistics
exclude:
  # Exclude files or packages matching their paths
  paths:
    - ^pkg/                  # exclude package `pkg/`
    - ^testing/              # exclude package `testing/`
    - ^internal/app/repo$    # exclude `repo` interfaces
    - ^internal/app/service$ # exclude `service` interfaces
 
# NOTES:
# - symbol `/` in all path regexps will be replaced by
#   current OS file path separator to properly work on Windows
