/*
Use DBML to define your database structure
Docs: https://dbml.dbdiagram.io/docs
*/

table users {
  id uuid [pk, default: `gen_random_uuid()`]
  name varchar(150) [not null]
  email varchar(50) [not null]
  username varchar(20) [not null]
  phone_number varchar(20) [not null]
  password varchar(255) [not null]

  created_at timestamp
  updated_at timestamp
  deleted_at timestamp

  indexes {
    phone_number [unique, type: btree]
    username [unique, type: btree]
    email [unique, type: btree]
    deleted_at [type: btree]
  }
}

table access_versionings {
  jti uuid [pk, default: `gen_random_uuid()`]
  parent_id uuid [ref: - access_versionings.jti, default: null]
  user_id uuid [ref: > users.id, not null]
  version integer
}
