version: "3.0"
services:
  moilerplate:
    build:
      context: ..
      dockerfile: docker/http.prod.dockerfile
    container_name: moilerplate-app
    image: moilerplate-app
    restart: always
    environment:
      - SERVER_HOST=0.0.0.0
      - SERVER_PORT=8082
      - LOG_PATH=logs/log.txt
      - DEFAULT_ROWS_PER_PAGE=25
      # DB
      - DB_HOST=moilerplate_pg
      - DB_PORT=5432
      - DB_NAME=moilerplate
      - DB_USER=postgres
      - DB_PASSWORD=verystrongpassword
      - DB_MAX_POOL_SIZE=5
      - DB_MAX_OPEN_CONN=5
      - DB_MAX_CONN_LIFETIME=1m
      # Rate Limitting
      - RATER_LIMIT=2
      - BURST_LIMIT=2
      - RATER_EVALUATION_INTERVAL=1m
      - RATER_DELETION_TIME=3m
      # Doorkeeper
      - DOORKEEPER_ISSUER=MOILERPLATE
      - DOORKEEPER_HASH_METHOD=SHA384
      - DOORKEEPER_SIGNING_METHOD=HMAC
      - DOORKEEPER_SIGN_SIZE=256
      # Secret key only for HMAC
      - DOORKEEPER_SECRET_KEY=verystrongsecretkey
      # Keep empty if you want to use HMAC
      - DOORKEEPER_CERT_PATH=
      # Admin key for accessing documentation resources or more
      - DOORKEEPER_ADMIN_KEY=verystrongpassword
      - DOORKEEPER_ACCESS_TOKEN_DURATION=1h
      - DOORKEEPER_REFRESH_TOKEN_DURATION=24h
    ports:
      - 8082:8082
    networks:
      - moilerplate-networks
    volumes:
      - ./:/app
    depends_on:
      - pg

  pg:
    image: postgres:latest
    container_name: moilerplate_pg
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=verystrongpassword
      - POSTGRES_DB=moilerplate
    restart: unless-stopped
    ports:
      - 5432:5432
    volumes:
      - moilerplate-pg-data:/var/lib/postgresql/data
    networks:
      - moilerplate-networks

  netdata:
    image: netdata/netdata:stable
    container_name: netdata
    pid: host
    network_mode: host
    restart: unless-stopped
    cap_add:
      - SYS_PTRACE
      - SYS_ADMIN
    security_opt:
      - apparmor:unconfined
    volumes:
      - moilerplate-netdataconfig:/etc/netdata
      - moilerplate-netdatalib:/var/lib/netdata
      - moilerplate-netdatacache:/var/cache/netdata
      - /etc/passwd:/host/etc/passwd:ro
      - /etc/group:/host/etc/group:ro
      - /etc/localtime:/etc/localtime:ro
      - /proc:/host/proc:ro
      - /sys:/host/sys:ro
      - /etc/os-release:/host/etc/os-release:ro
      - /var/log:/host/var/log:ro
      - /var/run/docker.sock:/var/run/docker.sock:ro
    environment:
      # For the environments of netdata, check your netdata console.
      - NETDATA_CLAIM_TOKEN=<FILL_IN>
      - NETDATA_CLAIM_URL=https://app.netdata.cloud
      - NETDATA_CLAIM_ROOMS=<FILL_IN>

volumes:
  moilerplate-pg-data:
  moilerplate-netdataconfig:
  moilerplate-netdatalib:
  moilerplate-netdatacache:
networks:
  moilerplate-networks:
